# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8b1f7f11951389776aae1a0194d6e5fd4e33cda794f8236f5c35b1f3af9275d653e43f9aefd9152daa5f571baed229e8cc12c8d214bf0b7fb9f7e22ace74d022

test:
  secret_key_base: a0da5a4daf6c2a3ee7085964d1d267c18d582ab5b16f2f64b657e2dcbd25303680f6c84e4659d625aad6b2128933d46d48b8b77c88be255df5f944ff8f05b533

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
